niteeshbhat/HbbTV_DVB_Conformance_Frontend

webfe/process.php
Error are highlighted with red and warnings with orange.
=> Highlight erors and warnings with colors

webfe/MPD_HbbTV_DVB.php, webfe/mpdprocessing.php, webfe/process.php
All the checks are in MPD_HbbTV_DVB.php file. All the checks so far are done for DVB coonformance.
Checks include the sections:
4.1, 4.2.2, 4.4, 4.5, 4.7.2, 6.1.1, 6.1.2.
=>  DVB MPD checks (not all but partial)

webfe/MPD_HbbTV_DVB.php, webfe/mpdprocessing.php
Only the DVB chec are done. All of them are in MPD_HbbTV_DVB.php file.
Small fixes are also introduced regarding the printing.
Sections: 6.3, 6.4, 7.1.1
=> Additional DVB MPD checks

webfe/MPD_HbbTV_DVB.php
Check says, if MPD includes an element that is declared with the profile being validated but element is not part of that profile. 
As a part of this, onDemand features are reported when validating against Hbbtv profile
Additionally, MPD report format is updated.
=> MPD Checks: Features of onDemand reported for HbbTV profile validation

webfe/MPD_HbbTV_DVB.php, webfe/conformancetest.php, webfe/mpdprocessing.php
php addtions: A value -true or warning or error  in the MPDConformance element of progress xml file.
JS addtions: read the above value and give link to the mpd report when warning or errors detected.
Also if only warning, then segment validation is carried out.
=> GUI changes for displaying MPD errors and warnings for Hbbtv-DVB

webfe/MPD_HbbTV_DVB.php
Code fixing and additional audio checks are done.
=>  Code fixing and additional audio checks

webfe/MPD_HbbTV_DVB.php, webfe/process.php
Also info with blue color sits on the top,
then warnings with orange and then
errors with red in the log file page.
=> Separated info, error , warnings with colors

webfe/MPD_HbbTV_DVB.php
Remaining DVB MPD checks regarding subtitles, encrypted content and recommendations for content provider are added.
=> Dvb checks

webfe/MPD_HbbTV_DVB.php
* Report(informational) if an MPD element is scoped by another profile (that the tool is not validating against).
- BaseURL
- UTCTiming
- EventStream and Event
=> Cross profile validation

webfe/MPD_HbbTV_DVB.php
*Report if any media type that is present in the MPD (e.g. video) is missing once the MPD has been processed for a specific profile.
=> Media types

webfe/MPD_HbbTV_DVB.php
The Period.SegmentList element shall not be present for period elements conforming to On Demand profile.
=> Small DVB MPD check addition

webfe/MPD_HbbTV_DVB.php
Checks from HbbTV 1.5 standard document ., section E.2.1, E.2.2, E.2.3, E.2.4, E.2.5.
=> Hbbtv mpd checks

webfe/CrossValidation_HbbTV_DVB.php, webfe/mpdprocessing.php, webfe/process.php
Cross check for representations section 4.3
=> Cross check for representations

webfe/CrossValidation_HbbTV_DVB.php, webfe/MPD_HbbTV_DVB.php, webfe/mpdprocessing.php
Adaptation Sets:
- Do they contain a consistent set of representations?
- All the examples in the given doc document
- "All representations in an adaptation set" checks
- Informational report on non-switchable representations
=> DVB - Adaptation Set Checks

webfe/CrossValidation_HbbTV_DVB.php
HbbTV Adaptation Set checks in Section E.3.2
and
Small optimization on the overall code structure
=> Some HbbTV Adaptation Set checks, small optimization on the overall code structure

webfe/CrossValidation_HbbTV_DVB.php
HbbTV Adaptation Set checks section E.4.2 
HbbTV Adaptation Set checks section E.3 (from Hybrid Broadcast Broadband TV specification)
=> HbbTV Adaptation Set checks

webfe/CrossValidation_HbbTV_DVB.php
Codec information:
Report on any resolutions used that are not in the tables of resoultions in 10.3 of the DVB DASH specification
=> Codec information: report on resolutions check acc. to table 10.3

webfe/CrossValidation_HbbTV_DVB.php
* Fix on HbbTV AdaptationSet reporting: removal of unneeded informational report
* Codec info addition
=> Fix on HbbTV AdaptationSet reporting, Codec info addition

webfe/CrossValidation_HbbTV_DVB.php, webfe/MPD_HbbTV_DVB.php
Small fixes on Adaptation Set checks
Codec information check: Are the codecs (in MPD and segments) actually supported by the specification?
Are the profiles of the codecs correct and supported by the specification?
=> Fixes on Adaptation Set checks and Checks for codec information

webfe/featuretable.html
Feature-based reporting completion and fixes for 'mode of use' checks.
=> Feature based reporting

webfe/CrossValidation_HbbTV_DVB.php, webfe/compare.php, webfe/mpdparsing.php, webfe/mpdprocessing.php
Period duration checking against accumulated segment duration. Corrected the merge conflict.
=>  Period duration checking against accumulated segment duration

webfe/CrossValidation_HbbTV_DVB.php, webfe/mpdprocessing.php
Segments check:
- Are the start times within the segments consistent with the timing indicated by the MPD?
=> Segment timing mp dinfo consistency

webfe/CrossValidation_HbbTV_DVB.php
* The formula used for this is:
LHS = Period@start + PTO
RHS = DecodeTime + CompositionTime - MediaTime
Check if LHS = RHS
* Fix is the consideration of CompositionTime and MediaTime in the calculation.
* Also, the check is made available only for non-dynamic content. Dynamic content check is left for Dynamic Service Validation software tool.
=> Fix for segment times' consistencies

webfe/MPD_HbbTV_DVB.php
Previous implementation was incomplete and wrong. Fix for this is provided with this PR.
=> Window of Availability - fix for UTCTiming element warning

webfe/MPD_HbbTV_DVB.php
DVB AudioChannelConfiguration element checks for ec-3, ac-4 and dts codecs are fixed.
=> Audio channel configuration

webfe/MPD_HbbTV_DVB.php
This PR includes the implementation of Section 10.5.2.2 of the DVB specification.
=> DVB - Associated adaptation set checks

webfe/CrossValidation_HbbTV_DVB.php, webfe/MPD_HbbTV_DVB.php, webfe/mpdparsing.php, webfe/mpdprocessing.php, webfe/mpdvalidation.php
Only the syntactical and logical checks are performed. The rest is targeted for the players.
=> MPD anchor checks according to DVB specifications

webfe/conformancetest.php
UI report providing:
- Informational report provided on UI for mpd validation
- Log icons changed to text file
=> Ui report cosmetic

webfe/CrossValidation_HbbTV_DVB.php, webfe/mpdprocessing.php
Need to find the line where the compInfo.txt files are completed
=> the new changes

webfe/CrossValidation_HbbTV_DVB.php, webfe/conformancetest.php, webfe/mpdprocessing.php
=> Fix for UI reporting when both cmaf and hbbtv-dvb conformance selected

webfe/conformancetest.php
=> UI tree fix for BrokenURL cases
